/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tunipharma_project.gui;
import tunipharma_project.DAO.PharmacieDAO;
import tunipharma_project.controller.*;
import tunipharma_project.entities.Pharmacie;

/**
 *
 * @author yassine
 */
public class List_pha_admin extends javax.swing.JFrame {

    /**
     * Creates new form List_pha_admin
     */
    public List_pha_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jsupprimerj = new javax.swing.JButton();
        jdetaillerj = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jsupprimer = new javax.swing.JButton();
        jdetailler = new javax.swing.JButton();
        jinsererj = new javax.swing.JButton();
        jprecedentj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane.setName("abc\n"); // NOI18N

        jTable2.setModel(new listPharmacienController2()

        );
        jScrollPane2.setViewportView(jTable2);

        jsupprimerj.setText("Supprimer");
        jsupprimerj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsupprimerjActionPerformed(evt);
            }
        });

        jdetaillerj.setText("Detailler");
        jdetaillerj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdetaillerjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jsupprimerj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jdetaillerj)
                .addGap(151, 151, 151))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdetaillerj)
                    .addComponent(jsupprimerj))
                .addGap(53, 53, 53))
        );

        jTabbedPane.addTab("Pharmacie de jour", jPanel3);

        jTable1.setModel(new listPharmacienController()

        );
        jScrollPane1.setViewportView(jTable1);

        jsupprimer.setText("Supprimer");
        jsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsupprimerActionPerformed(evt);
            }
        });

        jdetailler.setText("Detailler");
        jdetailler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdetaillerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jsupprimer)
                        .addGap(110, 110, 110)
                        .addComponent(jdetailler)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsupprimer)
                    .addComponent(jdetailler))
                .addGap(199, 199, 199))
        );

        jTabbedPane.addTab("Pharmacie de nuit", jPanel2);

        jinsererj.setText("Inserer");
        jinsererj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinsererjActionPerformed(evt);
            }
        });

        jprecedentj.setText("Precedent");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jprecedentj)
                        .addGap(78, 78, 78)
                        .addComponent(jinsererj)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jinsererj)
                    .addComponent(jprecedentj))
                .addContainerGap(348, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jinsererjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinsererjActionPerformed
        // TODO add your handling code here:
         
        setVisible(false);
        new Formulaire_pharmacien().setVisible(true);
    }//GEN-LAST:event_jinsererjActionPerformed

    private void jsupprimerjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsupprimerjActionPerformed
        // TODO add your handling code here:
        int ligne  =jTable2.getSelectedRow();
        PharmacieDAO pharmacieDAO =new PharmacieDAO();
        System.out.println(jTable2.getValueAt(ligne, 0));
       pharmacieDAO.delete((jTable1.getValueAt(ligne, 0)).toString());
        jTable1.setModel(new listPharmacienController2());
    }//GEN-LAST:event_jsupprimerjActionPerformed

    private void jsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsupprimerActionPerformed
        // TODO add your handling code here:
        int ligne  =jTable1.getSelectedRow();
        PharmacieDAO pharmacieDAO =new PharmacieDAO();
        System.out.println(jTable1.getValueAt(ligne, 0));
       pharmacieDAO.delete((jTable1.getValueAt(ligne, 0)).toString());
        jTable1.setModel(new listPharmacienController());
    }//GEN-LAST:event_jsupprimerActionPerformed

    private void jdetaillerjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdetaillerjActionPerformed
        // TODO add your handling code here:
        if (jTable2.getSelectedRow() != -1)
        {
            int ligne =jTable2.getSelectedRow();
            Pharmacie p=new Pharmacie();
            p.setNom(jTable2.getValueAt(ligne, 0).toString());
            p.setNom_pharmacien(jTable2.getValueAt(ligne,1).toString());
            p.setGouvernorat(jTable2.getValueAt(ligne,2).toString());
            p.setDelegation(jTable2.getValueAt(ligne, 3).toString());
            p.setAdress(jTable2.getValueAt(ligne, 4).toString());
            p.setN_tel(Integer.parseInt(jTable2.getValueAt(ligne, 5).toString()));
            p.setFax(Integer.parseInt(jTable2.getValueAt(ligne,6).toString()));
            p.setA_mail((jTable2.getValueAt(ligne, 7).toString()));
            p.setCNAM(Integer.parseInt(jTable2.getValueAt(ligne, 8).toString()));
            p.setGarde(1);

            new detaille_pharmacien(p).setVisible(true);
        }
    }//GEN-LAST:event_jdetaillerjActionPerformed

    private void jdetaillerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdetaillerActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() != -1)
        {
            int ligne =jTable1.getSelectedRow();
            Pharmacie p=new Pharmacie();
            p.setNom(jTable1.getValueAt(ligne, 0).toString());
            p.setNom_pharmacien(jTable1.getValueAt(ligne,1).toString());
            p.setGouvernorat(jTable1.getValueAt(ligne,2).toString());
            p.setDelegation(jTable1.getValueAt(ligne, 3).toString());
            p.setAdress(jTable1.getValueAt(ligne, 4).toString());
            p.setN_tel(Integer.parseInt(jTable1.getValueAt(ligne, 5).toString()));
            p.setFax(Integer.parseInt(jTable1.getValueAt(ligne,6).toString()));
            p.setA_mail((jTable1.getValueAt(ligne, 7).toString()));
            p.setCNAM(Integer.parseInt(jTable1.getValueAt(ligne, 8).toString()));
            p.setGarde(0);

            new detaille_pharmacien(p).setVisible(true);
        }
    }//GEN-LAST:event_jdetaillerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(List_pha_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(List_pha_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(List_pha_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(List_pha_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new List_pha_admin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jdetailler;
    private javax.swing.JButton jdetaillerj;
    private javax.swing.JButton jinsererj;
    private javax.swing.JButton jprecedentj;
    private javax.swing.JButton jsupprimer;
    private javax.swing.JButton jsupprimerj;
    // End of variables declaration//GEN-END:variables
}
